services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASES_USER}
      POSTGRES_PASSWORD: ${DATABASES_PASSWORD}
      POSTGRES_DB: ${DATABASES_NAME}

  cache:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always